config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :products do
    resources :bookings, only: %i[new create edit update]
    resources :reviews, only: [:new, :create]

    collection do
      get 'myProducts'
    end
  end

  resources :alerts, only: :index

  resources :bookings, only: :index do
    member do
      patch :accept
      patch :decline
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :status, inclusion: { in: %w[pending accepted declined] }
  validate :minimum_24h
  validate :not_in_past

  def minimum_24h
    errors.add(:base, "must last more than 24h") if end_date < start_date + 24.hours
  end

  def not_in_past
    errors.add(:base, "can't be in past") if start_date < Date.today && end_date < Date.today
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_many_attached :photos

  validates :title, :price, :category, :description, presence: true

  def rating
    reviews.average(:rating)&.round || 0
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :reserved_products, through: :bookings, source: :product

  has_many :bookings_as_owner, through: :products, source: :bookings
  has_many :bookings_as_lodger, class_name: "Booking", foreign_key: "user_id", dependent: :destroy

  has_one_attached :photo

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_product, only: %i[new create]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.product = @product
    @booking.user = current_user

    if @booking.save
      redirect_to products_path
    else
      render :new, layout: false, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    @booking.product = @product
    @booking.user = current_user
    redirect_to bookings_path
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    redirect_to bookings_path
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @products = Product.all
    if current_user
    @my_products = current_user.products
    inch = []
      if @products.length > 0
        @my_products.each do |product|
          product.bookings.each do |booking|
            inch << booking
          end
        end
        inch.each do |book|
          @book = book
        end
     end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @products = Product.all
    @category = Category.new

    if params[:query].present?
      sql_subquery = <<~SQL
        products.title ILIKE :query
        OR products.description ILIKE :query
        OR categories.name ILIKE :query
      SQL
      @products = @products.joins(:category).where(sql_subquery, query: "%#{params[:query]}%")
    end

    if params[:category].present?
      @products = @products.joins(:category).where("name ILIKE ?", "%#{params[:category]}%")
    end

    if params[:max_price].present?
      min_price = 0
      max_price = params[:max_price].to_i
      @products = @products.where(price: min_price..max_price)
    end

  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    @users = User.all
    @booking = Booking.new
    @review = Review.new
    @bookings = @product.bookings

    @booking_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end

  end

  def new
    @product = Product.new
  end

  def myProducts
    # @products = current_user.products
    @products = Product.where(user: current_user)
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :category_id, :description, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product

  def create
    @review = Review.new(review_params)
    @review = @product.reviews.new(review_params)
    @review.user = current_user

    if @product.reviews.exists?(user_id: current_user.id)
      flash[:alert] = "Vous avez déjà commenté ce produit."
      redirect_to @product
    else
      if @review.save
        flash[:notice] = "Votre commentaire a été ajouté avec succès."
        redirect_to @product
      else
        flash[:alert] = "Erreur lors de l'ajout de votre commentaire."
        render 'products/show'
      end
    end
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:description, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div class="col">
  <div class="position-relative card bg-light" >
    <% if booking.status == "pending" %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-warning p-2">
        <%= booking.status.capitalize %>
      </div>
    <% elsif booking.status == "accepted" %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-success p-2 text-light">
        <%= booking.status.capitalize %>
      </div>
    <% else %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-danger p-2">
        <%= booking.status.capitalize %>
      </div>
    <% end %>

    <% if booking.product.photos.attached? %>
      <%= cl_image_tag booking.product.photos.first.key, class: "card-img-top object-fit-contain p-2", height: 150 %>
    <% else %>
      <img class="card-img-top" src="https://www.couturierparisien.fr/574-large_default/chemise-homme-blanche-popeline-de-coton-col-francais.jpg" alt="Card image cap" width=10% height=10%>
    <% end %>

    <div class="card-body bg-light pb-0">
        <h5 class="card-title line-clamp-1 product-title"><%= booking.product.title.capitalize %></h5>
        <p class="card-text line-clamp-3 product-description"><%= booking.product.description %></p>
        <p class="product-category"><i class="fa-solid fa-tag"></i> <%= booking.product.category.name.upcase %></p>
        <p class="product-price"><small class="text-dark">Total price: <i class="fa-solid fa-dollar-sign"></i> <%= booking.total_price %></small></p>
        <p>From: <%= booking.start_date.strftime("%A %d %B") %> </p>
        <p>To: <%= booking.end_date.strftime("%A %d %B") %></p>
        <p>Total day: <%= (booking.end_date - booking.start_date).to_i  %> days</p>
        <% remaining_days = (booking.end_date - Date.today).to_i %>
        <%= remaining_days > 0 ? "#{remaining_days} days left" : "Réservation terminée" %> <br>
        <div class="d-flex justify-content-center">
          <%= link_to "View details", product_path(booking.product), class: "btn btn-flat", style: "border: 1px solid #000; padding: 10px 20px; border-radius: 5px;" %>
        </div>
    </div>

    <% if booking.status == "pending" %>
      <div class="d-flex mt-3 justify-content-center">
        <%= button_to "Accepter", accept_booking_path(booking), method: :patch, class: "btn btn-success mx-3" %>
        <%= button_to "Refuser", decline_booking_path(booking), method: :patch, class: "btn btn-danger" %>
      </div>
    <% end %>


  </div>
</div>

app/views/bookings/_bookingLodger.html.erb
<div class="col">
  <div class="position-relative card bg-light">
        <% if booking.status == "pending" %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-warning p-2">
        <%= booking.status.capitalize %>
      </div>
    <% elsif booking.status == "accepted" %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-success p-2 text-light">
        <%= booking.status.capitalize %>
      </div>
    <% else %>
      <div class="position-absolute top-3 end-3 rounded-pill bg-danger p-2">
        <%= booking.status.capitalize %>
      </div>
    <% end %>

    <% if booking.product.photos.attached? %>
      <%= cl_image_tag booking.product.photos.first.key, class: "card-img-top object-fit-contain p-2", height: 150 %>
    <% else %>
      <img class="card-img-top" src="https://www.couturierparisien.fr/574-large_default/chemise-homme-blanche-popeline-de-coton-col-francais.jpg" alt="Card image cap" width=10% height=10%>
    <% end %>

    <div class="card-body bg-light pb-0 ">
        <h5 class="card-title line-clamp-1 product-title"><%= booking.product.title.capitalize %></h5>
        <p class="card-text line-clamp-3 product-description"><%= booking.product.description %></p>
        <p class="product-category"><i class="fa-solid fa-tag"></i> <%= booking.product.category.name.upcase %></p>
        <p class="product-price"><small class="text-dark">Total price: <i class="fa-solid fa-dollar-sign"></i> <%= booking.total_price %></small></p>
        <p>From: <%= booking.start_date.strftime("%A %d %B") %> </p>
        <p>To: <%= booking.end_date.strftime("%A %d %B") %></p>
        <p>Total day: <%= (booking.end_date - booking.start_date).to_i  %> days</p>
        <% remaining_days = (booking.end_date - Date.today).to_i %>
        <%= remaining_days > 0 ? "#{remaining_days} days left" : "Réservation terminée" %>
        <div class="d-flex justify-content-center">
          <%= link_to "View details", product_path(booking.product), class: "btn btn-flat", style: "border: 1px solid #000; padding: 10px 20px; border-radius: 5px;" %>
        </div>    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [@product, @booking], html: { data: { fetch_target: :form, action: "submit->fetch#perform" } } do |f| %>
  <div class="modal-body">
    <div class="form-container" data-booking-form-target="togglable">
      <%= f.input :start_date,  as: :string, input_html: { data: { controller: "datepicker", datepicker_unavailable_dates_value: booking_dates.to_json, booking_form_target: 'start', action: "change->booking-form#compute" } } %>
      <%= f.input :end_date,  as: :string, input_html: { data: { controller: "datepicker", datepicker_unavailable_dates_value: booking_dates.to_json, booking_form_target: 'end', action: "change->booking-form#compute" } } %>
      <%= f.input :total_price, label: false, input_html: {class: 'd-none', data: { booking_form_target: 'totalPriceInput' } } %>
    </div>
  </div>
  <div class="modal-footer justify-content-between">
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <p data-booking-form-target="day"></p>
    <p data-booking-form-target="totalPrice"></p>
    <div class="btn-form">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      <%= f.submit "Book", class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/bookings/_review_form.html.erb
<div class="modal fade" id="reviewModal" tabindex="-1">
  <%= simple_form_for [@product, @review] do |f| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5">New review</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= f.input :description  %>
          <%= f.input :rating, collection: 1..5  %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="container position-relative">
  <h1 class="text-center my-4">My bookings (as owner)</h1>
  <div class="row">
    <% if current_user.bookings_as_owner.length >= 1 %>
      <% current_user.bookings_as_owner.each do |booking| %>
        <%= render booking  %>
      <% end %>
    <% else %>
      <h6 class="text-center">No bookings yet</h6>
    <% end %>
  </div>


<div class="container position-relative">
  <h1 class="text-center my-4">My bookings (as owner)</h1>
  <div class="row">
    <% if current_user.bookings_as_owner.length >= 1 %>
      <% current_user.bookings_as_owner.each do |booking| %>
        <%= render booking  %>
      <% end %>
    <% else %>
      <h6 class="text-center">No bookings yet</h6>
    <% end %>
  </div>



  <%= link_to root_path, class: "btn btn-outline-secondary rounded-circle position-absolute top-0 start-0" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
</div>

app/views/bookings/new.html.erb
<%= render "form", product: @product, booking: @booking, booking_dates: @booking_dates %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alibobo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="icon" href="<%= asset_path 'logogo.png' %>" type="image/png">

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.4) 95%, rgba(244, 240, 239, 1) 100%), url(https://img.lonelyplanet.fr/s3fs-public/styles/wide/public/2023-12/souks.jpg.webp?itok=qiNx1jRI);">
  <div class="container">
    <h1><strong>AliBobo</strong></h1>
    <p>Rent everything you want</p>
      <div class="row">
        <div class="col-sm-8 my-3 form-outline" data-mdb-input-init>
          <%= form_with url: products_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                params[:query],
                class: "form-control border border-light bg bg-transparent text-light rounded-left nav",
                placeholder: "What do you want ?"
            %>
          <%= submit_tag "Search", name: "", class: "btn-search btn btn-light fw-bold rounded-right nav-btn" %>
            <%# <i class="fa-solid fa-magnifying-glass"></i> %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<div class="back">
      <div class="container">
        <div class="contai">
      <p>
          <span>
            <strong> Top products to rent </strong>
          </span>
      </p>
    </div>
    <div class="d-flex flex-wrap justify-content-center">
      <% @products.sample(6).each do |product| %>
        <div class="card-front col-10 col-md-5 col-lg-3 m-3 shadow-sm" style="border-radius: 10px; transition: transform 0.3s; background-color: #dbbfba; border-style: none;">
          <%= link_to product_path(product) do %>
            <% if product.photos.attached? %>
              <%= cl_image_tag product.photos.first.key, class: "img-card card-img-top object-fit-contain p-2", height: 150 %>
            <% else %>
              <img class="img-card card-img-top object-fit-contain p-2" src="https://www.couturierparisien.fr/574-large_default/chemise-homme-blanche-popeline-de-coton-col-francais.jpg" alt="Default product image" style="width: 100%; height: 150px;">
            <% end %>
            <div class="card-body-front text-center">
              <h1 class="card-title line-clamp-1 product-title"><%= product.title.capitalize %></h1>
              <p class="product-category"><i class="fa-solid fa-tag"></i> <%= product.category.name %></p>
              <p class="product-price"><small class="text-dark"><i class="fa-solid fa-dollar-sign"></i> <%= product.price %></small></p>
              <div class="d-flex-rating">
                <div class="rating">
                  <% if product.rating.present? %>
                    <% (1..5).each do |i| %>
                      <p><i class="<%= i <= product.rating ? 'fa-solid' : 'fa-regular' %> fa-star"></i></p>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div class="col ">
  <div class="container-front">
    <%= link_to product_path(product) do %>
      <div class="card-front">
        <% if product.photos.attached? %>
          <%= cl_image_tag product.photos.first.key, class: "img-card card-img-top object-fit-contain p-2", height: 150 %>
        <% else %>
          <img class="img-card card-img-top" src="https://www.couturierparisien.fr/574-large_default/chemise-homme-blanche-popeline-de-coton-col-francais.jpg" alt="Card image cap" >
        <% end %>
        <div class="card-body-front">
            <h3 class="card-title line-clamp-1 product-title overflow-hidden text-top" style="height: 30px"><%= product.title.capitalize %></h3>
            <p class="card-text line-clamp-2 product-description px-2 overflow-auto" style="height: 50px"><%= product.description %></p>
            <p class="product-category"><i class="fa-solid fa-tag"></i> <%= product.category.name %></p>
            <p class="product-price"><small class="text-dark"><i class="fa-solid fa-dollar-sign"></i> <%= product.price %></small></p>
            <div class="d-flex-rating">
              <div class="rating">
                  <% if product.rating.present? %>
                    <% (1..5).each do |i| %>
                        <p><i class="<%= i <= product.rating ? 'fa-solid' : 'fa-regular' %> fa-star"></i></p>
                    <% end %>
                  <% end %>
              </div>
            </div>
        </div>
      </div>
     <% end  %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container mt-4 px-5 position-relative">
<div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
  <%= simple_form_for @product do |f| %>
  <%= f.input :title %>
  <%= f.input :price %>
  <%= f.association :category %>
  <%= f.input :description %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Edit my product", class: "btn btn-primary" %>
<% end %>
 <%= link_to product_path(@product), class: "btn btn-outline-secondary rounded-circle position-absolute top-0 start-0" do %>
  <i class="fas fa-arrow-left"></i>
<% end %>
   </div>
  </div>

</div>

app/views/products/myProducts.html.erb
<h1 class="text-center mt-2" >My Products</h1>

<div class="container mt-2">
  <div class="row d-flex flex-wrap justify-content-center">
    <% if @products.length >= 1 %>
      <% @products.each do |product| %>
        <div class="col-md-4 mb-4">
            <%= render product %>
        </div>
      <% end %>
    <% else %>
      <div class="col-12 text-center mt-4">
        <h6>No products yet, <%= link_to "Add product", new_product_path %></h6>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container d-inline-block mx-5" data-controller="booking-form">
  <%= link_to "<i class='fa-solid fa-arrow-left'></i>".html_safe, products_path, class: 'btn btn-outline-secondary rounded-circle mx-4 mt-2 justify-content-start' %>
  <div class="justify-content-between py-4" style="height: 50%">
  <div class="container">
    <div class="img-container">
        <% if @product.photos.first != nil%>
          <%= cl_image_tag @product.photos.first.key %>
          <div class="right-part">
            <% @product.photos[1..2].each do |img| %>
              <div class="small-img">
                <%= cl_image_tag img.key, class: "img" %>
              </div>
            <% end %>
          </div>
        <%end %>
    </div>

    <div class="card shadow h-auto bg bg-light" style="width: 100%">

      <div class="card-body d-flex flex-column justify-content-between h-auto">
        <div>
          <h2><strong><%= @product.title %></strong></h2>
          <h3 class="my-3"> $ <span data-booking-form-target="price" data-price="<%= @product.price %>"><%= @product.price %></span> / day</h3>
          <h6 class="my-3 overflow-auto" style="height: 100px"><%= @product.description %></h6>
        </div>
      </div>

  <div class="d-flex mx-3">
      <% if @product.rating.present? %>
          <% (1..5).each do |i| %>
              <p><i class="<%= i <= @product.rating ? 'fa-solid' : 'fa-regular' %> fa-star"></i></p>
          <% end %>
           <p class="mx-2"> <%= @reviews.count %> reviews</p>
      <% end %>
  </div>



    <div>
  <% @product.reviews.each do |review| %>
    <div class="d-flex align-items-center mb-4">
      <div class="me-3 mx-4">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if review.user.photo.attached? %>
            <%= cl_image_tag review.user.photo.key, class: "avatar" %>
          <% else %>
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          <% end %>
        </a>
      </div>

      <div class="me-3">
        <div class="d-flex align-items-center">
          <% (1..5).each do |i| %>
            <i class="<%= i <= review.rating ? 'fa-solid' : 'fa-regular' %> fa-star"></i>
          <% end %>
        </div>

        <div>
          <h6 class="mb-0"><%= review.description %></h6>
        </div>
      </div>
    </div>
  <% end %>
</div>



        <div class="buttons d-flex justify-content-start px-2 pb-2">
          <% if @product.in? current_user.reserved_products %>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#reviewModal">
              Add a review
            </button>
            <%= render "bookings/review_form", product: @product, review: @review %>
          <% else %>
            <% if @product.user != current_user %>
              <button type="button" class="btn btn-primary fw-bold mx-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Book
              </button>
            <% end %>
          <% end %>
          <div>
            <% if @product.user == current_user %>
              <%= link_to "Edit my product", edit_product_path(@product), class: 'btn btn-outline-primary' %>
              <%= link_to "Delete my product", product_path(@product), class: 'btn btn-outline-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Book</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div data-controller="fetch">
          <%= render "bookings/form", product: @product, booking: @booking, booking_dates: @booking_dates %>
        </div>
      </div>
    </div>
  </div>
</div>
 </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top shadow-sm rounded-bottom">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logogo.png" %>
    <% end %>



    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav ms-auto align-items-center">
          <li class="nav-item active justify-content-start">
            <%= link_to "Home",root_path, class: "nav-link fw-bold" %>
          </li>
        </ul>
        <ul class="navbar-nav me-auto align-items-center">
          <li class="nav-item">
            <%= link_to "All products", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Rent a product",new_product_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar position-relative mx-3" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
             <%= cl_image_tag current_user.photo.key, class:"avatar border border-light" %>
              <% else %>
             <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar ", alt: "dropdown menu" %>
            <% end %>
              <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                <span class="visually-hidden">New alerts</span>
              </span>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class="text-center border-bottom pb-1"><strong><%= current_user.full_name%></strong></p>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "My products", myProducts_products_path, class: "dropdown-item" %>
              <%= link_to "<i class='fa-solid fa-right-to-bracket'></i>".html_safe + "  Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-danger " %>
            </div>

          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-outline btn-ghost" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>